- README.md
- apps/cli/package.json
- apps/docs/pages/authentication.mdx
- apps/docs/pages/tech-stack.mdx
- apps/docs/pages/wish-list.mdx
- apps/docs/pages/workflow/development.mdx
- apps/docs/pages/workflow/production.mdx
There were some markdown issues in the supabase docs that were also causing the title of some pages in the browser to be incorrect. Also updated the wishlist section of the docs & readme.
Bumped the cli package version so it does get published by npm. Infact the previous workflow run failed with this:
> Fixed supabase docs and cli

- .github/workflows/backend.yml
- .github/workflows/cli.yml
- .github/workflows/docs.yml
- .github/workflows/expo.yml
- .github/workflows/next.yml
- apps/expo/app.json
- Added workflow_dispatch to github actions
- Updated eas projectId
- Check version number change before publishing to npm
- Added publish to Github package repository for `create-t4-app`
> [Feature][Timothy/Albbus] EAS Workflow improvements

- .github/workflows/expo.yml
I guess the eas command is not being fired in the right location since it tries to initialize a new eas project.
> [Feature] EAS build fix

- .github/workflows/expo.yml
- apps/docs/pages/workflow/production.mdx
Removed an unused eas init and added more docs with the eas setup instructions.
> Removed eas init & added docs

- README.md
- apps/docs/pages/index.mdx
- apps/docs/pages/wish-list.mdx
> Chore - Update features in README.Md and Docs

- packages/api/src/context.ts
This provides typing for email, phone, role, session_id, etc.
> Update context.ts to support extended Supabase JWT type support

- .github/actions/pnpm-install/action.yml
Fixed condition + working-directory
> pnpm install action update & fix

- package.json
> fix: recursive upgrade tamagui

- apps/vscode/src/extension.ts
I refactored the vscode extension to be more readable and include more comments.
> [Chore] Refactored vscode extension

- .github/workflows/autoupdate.yml
This implements the [autoupdate](https://github.com/marketplace/actions/auto-update) github action.
The autoupdate action works for all the branches in the repo and updates the PR to the new destination branch status if some commits get pushed to it.
> [Feature] Automatic branch update for PRs

- .vscode/settings.json
- apps/vscode/README.md
- apps/vscode/package.json
- apps/vscode/src/extension.ts
This implements the feature request #57
> [Vscode] Added conversion for different input string formats

- packages/api/seed/seed.sql
- packages/app/features/virtualized-list/screen.tsx
- packages/app/utils/number.ts
- packages/ui/src/list/index.tsx
- packages/ui/src/list/index.web.tsx
- Connect to trpc.car.all query
- Update web implementation to use tamagui stack wrapper
- Update web implementation to work with onScroll
- Add back button header with animation height on scroll
I also updated the database table names to lowercase plural to match the naming in the seed file. If you prefer, I could resubmit with keeping the table names and just updating the seed file.
Feel free to close if you want to go in a different direction. No worries. Thanks for all of the work on this project so far!
> Update virtualized list demo

- packages/app/features/sign-in/screen.tsx
In reference to the issue https://github.com/timothymiller/t4-app/issues/76#issue-1902738401, I tested the options parameter with other provides as well as Google and found removing this will fix the error that will fix the issue permanently.
> Removed options which was causing Google Auth error

- apps/expo/package.json
- apps/next/package.json
- packages/app/package.json
- packages/ui/package.json
- pnpm-lock.yaml
Bumped all the Tamagui dependencies to fix a CI error present in https://github.com/timothymiller/t4-app/actions/runs/6292139257/job/17081245763 (`Module not found: Can't resolve '../public/tamagui.css'`)
> Bumped tamagui dependencies

- apps/vscode/package.json
- pnpm-lock.yaml
Fixing `ERR_PNPM_ERR_PNPM_TARBALL_INTEGRITY  The lockfile is broken! Resolution step will be performed to fix it.` that was happening during `pnpm i`
> [Bug] Fixed pnpm-lock

- packages/api/src/routes/user.ts
- packages/app/utils/auth/index.ts
Replace a couple long conditional statements used for sign in with ts-pattern match.
> Refactor some auth code with ts-pattern

- packages/api/src/worker.ts
> Add actionable info to missing APP_URL warning

- packages/api/src/utils/jwt.ts
FYI, these type errors exist in the original - https://github.com/pilcrowOnPaper/oslo/blob/main/src/jwt/index.ts#L94-L95
See https://github.com/pilcrowOnPaper/oslo/issues/12 for discussion.
> Typescript fixes for patched oslo/jwt

- packages/api/src/worker.ts
Hey I just noted that a fresh repo will be dirty bc of my change.
> Fix formatting causing version control change

- README.md
- apps/expo/app.config.ts
- apps/expo/eas.json
- package.json
- packages/app/provider/solito-image/index.tsx
Just bringing lucia up to date with master. Oslo, arctic and lucia have some small updates so I can get those up to the latest versions in another PR. The lucia changes include removing the framework adapters... but we were already using a custom version anyway so that didn't affect us. Everything else has been around adding documentation for v3. Seems like that is moving quickly. I bet it will be released in q1 2024 if not by the end of this month.
> Lucia upstream update 20231209

- packages/app/features/password-reset/screen.tsx
- packages/app/utils/auth/index.ts
> Fix sign-in link after password reset

- packages/api/src/utils/password/argon2.ts
It seems like something changed with workerd that caused the `await wasi.start()` method to start throwing errors like "The script will never generate a response"
Maybe wasi.start is no longer a promise due to new wasm optimizations? Just a guess. Having it await the wasi start along with the stderr and stdout streams seems to resolve the error.
> [lucia] Fix argon2 hashing
